name = "modern-blog-nextjs"
compatibility_date = "2025-01-27"

# Cloudflare Pages configuration
pages_build_output_dir = "out"

# Enable Node.js compatibility for ISR
compatibility_flags = ["nodejs_compat"]
