name = "modern-blog-nextjs"
compatibility_date = "2025-01-27"

[build]
command = "npm run build"
publish = ".next"

[[build.environment_variables]]
NODE_VERSION = "18"

# Enable Node.js compatibility for ISR
compatibility_flags = ["nodejs_compat"]

[env.production]
compatibility_date = "2025-01-27"